function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 29-Jan-2019 09:17:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0 0 1],'MarkerEdgeColor',[1 1 0],...
    'MarkerSize',10,...
    'Marker','v',...
    'LineWidth',2,...
    'LineStyle','-.',...
    'Color',[0 0 1]);

box(axes1,'on');
